"""
Topic-Level Resource Discovery Tools (Step 3C)

Provides:
- deterministic query parameter construction
- Tavily search provider abstraction
- deterministic fake search client
- URL validation
- resource normalization
- concept-aware relevance ranking

The LLM is responsible for understanding the learner/topic context and producing
a SearchQueryPlan. This module remains deterministic and does not make LLM calls.
"""

from abc import ABC, abstractmethod
import hashlib
import re
from typing import List, Optional, Set, Dict, Any
from urllib.parse import urlparse

import httpx

from app.core.config import settings
from app.schemas.models import (
    TopicResourceDiscoveryRequest,
    SearchQueryPlan,
    LearningResource,
    ResourceType,
    ResourceDifficulty,
)


# Number of candidates retrieved from Tavily BEFORE deterministic ranking.
# We want a reasonably large candidate pool so ranking has room to work.
RESOURCE_SEARCH_CANDIDATE_COUNT: int = 20


class ResourceProviderError(Exception):
    """Raised when an external resource provider encounters an unrecoverable error."""

    pass


# ---------------------------------------------------------------------------
# Domain helpers
# ---------------------------------------------------------------------------

def _clean_domain(domain_str: str) -> Optional[str]:
    """Sanitize a domain string."""

    if not domain_str or not isinstance(domain_str, str):
        return None

    d = domain_str.strip().lower()

    d = re.sub(r"^https?://", "", d)
    d = d.split("/")[0]
    d = d.split("?")[0]
    d = d.strip()

    if "." in d and not any(
        c in d
        for c in [
            " ",
            "*",
            ":",
            ";",
            "<",
            ">",
            '"',
            "'",
        ]
    ):
        return d

    return None


def _extract_domain(url: str) -> str:
    """Extract normalized hostname from URL."""

    try:
        parsed = urlparse(url)
        return parsed.netloc.lower().removeprefix("www.")
    except Exception:
        return ""


def _domain_matches(domain: str, candidates: List[str]) -> bool:
    """
    Returns True if the URL domain matches one of the candidate domains.

    Supports subdomains, e.g.
        docs.python.org
    matching:
        python.org
    """

    normalized_domain = domain.lower().removeprefix("www.")

    for candidate in candidates:
        clean = _clean_domain(candidate)

        if not clean:
            continue

        clean = clean.removeprefix("www.")

        if normalized_domain == clean:
            return True

        if normalized_domain.endswith("." + clean):
            return True

    return False


# ---------------------------------------------------------------------------
# Query builder
# ---------------------------------------------------------------------------

class QueryBuilder:
    """
    Deterministic translator from SearchQueryPlan to Tavily-compatible
    search parameters.

    The LLM has already generated the semantic query.
    This class only translates that plan into provider parameters.
    """

    @staticmethod
    def build_youtube_search_parameters(
        plan: SearchQueryPlan,
        request: TopicResourceDiscoveryRequest,
    ) -> Dict[str, Any]:
        """
        Builds Tavily parameters for YouTube discovery.

        We deliberately keep the query exactly as generated by the
        Search Query Agent instead of modifying it here.
        """

        return {
            "query": plan.youtube_query.strip(),
            "include_domains": ["youtube.com"],
            "max_results": RESOURCE_SEARCH_CANDIDATE_COUNT,
            "search_depth": "advanced",
        }

    @staticmethod
    def build_general_search_parameters(
        plan: SearchQueryPlan,
        request: TopicResourceDiscoveryRequest,
    ) -> Dict[str, Any]:
        """
        Builds Tavily parameters for general-web discovery.

        Preferred domains are NOT used as include_domains.

        Why?

        include_domains would restrict Tavily to only those domains and could
        accidentally hide excellent resources from universities or other
        authoritative sources.

        Instead, preferred domains are used by the deterministic ranking layer.
        """

        params: Dict[str, Any] = {
            "query": plan.general_query.strip(),
            "max_results": RESOURCE_SEARCH_CANDIDATE_COUNT,
            "search_depth": "advanced",
        }

        if plan.excluded_domains:
            clean_excluded = [
                _clean_domain(domain)
                for domain in plan.excluded_domains
            ]

            valid_excluded = [
                domain
                for domain in clean_excluded
                if domain
            ]

            if valid_excluded:
                params["exclude_domains"] = valid_excluded[:20]

        return params


# ---------------------------------------------------------------------------
# Search provider abstraction
# ---------------------------------------------------------------------------

class ResourceSearchProvider(ABC):
    """Abstract interface for topic-level learning resource providers."""

    @abstractmethod
    def search_youtube(
        self,
        query: str,
        max_results: int = RESOURCE_SEARCH_CANDIDATE_COUNT,
        **kwargs: Any,
    ) -> List[Dict[str, Any]]:
        """Search YouTube resources."""
        pass

    @abstractmethod
    def search_general(
        self,
        query: str,
        max_results: int = RESOURCE_SEARCH_CANDIDATE_COUNT,
        **kwargs: Any,
    ) -> List[Dict[str, Any]]:
        """Search general web resources."""
        pass


# ---------------------------------------------------------------------------
# Tavily implementation
# ---------------------------------------------------------------------------

class TavilySearchClient(ResourceSearchProvider):
    """
    Production Tavily Search API client.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_url: Optional[str] = None,
        timeout: float = 10.0,
    ):
        self.api_key = (
            api_key
            if api_key is not None
            else settings.TAVILY_API_KEY or ""
        )

        self.api_url = api_url or settings.TAVILY_API_URL
        self.timeout = timeout

    def search_youtube(
        self,
        query: str,
        max_results: int = RESOURCE_SEARCH_CANDIDATE_COUNT,
        include_domains: Optional[List[str]] = None,
        exclude_domains: Optional[List[str]] = None,
        search_depth: str = "advanced",
        **kwargs: Any,
    ) -> List[Dict[str, Any]]:

        if not self.api_key:
            raise ResourceProviderError(
                "Tavily API key is not configured."
            )

        payload: Dict[str, Any] = {
            "api_key": self.api_key,
            "query": query,
            "include_domains": include_domains or ["youtube.com"],
            "max_results": max(1, min(20, max_results)),
            "search_depth": search_depth or "advanced",
        }

        if exclude_domains:
            payload["exclude_domains"] = exclude_domains

        return self._execute_search(payload)

    def search_general(
        self,
        query: str,
        max_results: int = RESOURCE_SEARCH_CANDIDATE_COUNT,
        include_domains: Optional[List[str]] = None,
        exclude_domains: Optional[List[str]] = None,
        search_depth: str = "advanced",
        **kwargs: Any,
    ) -> List[Dict[str, Any]]:

        if not self.api_key:
            raise ResourceProviderError(
                "Tavily API key is not configured."
            )

        payload: Dict[str, Any] = {
            "api_key": self.api_key,
            "query": query,
            "max_results": max(1, min(20, max_results)),
            "search_depth": search_depth or "advanced",
        }

        if include_domains:
            payload["include_domains"] = include_domains

        if exclude_domains:
            payload["exclude_domains"] = exclude_domains

        return self._execute_search(payload)

    def _execute_search(
        self,
        payload: Dict[str, Any],
    ) -> List[Dict[str, Any]]:

        try:
            with httpx.Client(timeout=self.timeout) as client:
                response = client.post(
                    self.api_url,
                    json=payload,
                )

                if response.status_code != 200:
                    sanitized_text = self._sanitize(response.text)

                    raise ResourceProviderError(
                        f"Tavily API responded with status "
                        f"{response.status_code}: {sanitized_text}"
                    )

                data = response.json()

                return data.get("results", [])

        except httpx.HTTPError as exc:
            sanitized_err = self._sanitize(str(exc))

            raise ResourceProviderError(
                f"HTTP communication failure with Tavily: "
                f"{sanitized_err}"
            ) from None

    def _sanitize(self, text: str) -> str:

        if self.api_key and self.api_key in text:
            return text.replace(
                self.api_key,
                "[REDACTED_API_KEY]",
            )

        return text


# ---------------------------------------------------------------------------
# Fake provider
# ---------------------------------------------------------------------------

class FakeTavilySearchClient(ResourceSearchProvider):
    """
    Deterministic in-memory provider for tests/offline environments.
    """

    def __init__(
        self,
        simulate_youtube_error: bool = False,
        simulate_general_error: bool = False,
    ):
        self.simulate_youtube_error = simulate_youtube_error
        self.simulate_general_error = simulate_general_error

        self._youtube_catalog = self._build_youtube_catalog()
        self._general_catalog = self._build_general_catalog()

    def search_youtube(
        self,
        query: str,
        max_results: int = RESOURCE_SEARCH_CANDIDATE_COUNT,
        **kwargs: Any,
    ) -> List[Dict[str, Any]]:

        if self.simulate_youtube_error:
            raise ResourceProviderError(
                "Simulated Tavily YouTube search failure."
            )

        if not query or not query.strip():
            return []

        tokens = self._tokenize(query)

        matches = []

        for item in self._youtube_catalog:

            item_tokens = self._tokenize(
                f"{item['title']} {item.get('content', '')}"
            )

            if tokens.intersection(item_tokens):
                matches.append(item)

        return matches[:max_results]

    def search_general(
        self,
        query: str,
        max_results: int = RESOURCE_SEARCH_CANDIDATE_COUNT,
        **kwargs: Any,
    ) -> List[Dict[str, Any]]:

        if self.simulate_general_error:
            raise ResourceProviderError(
                "Simulated Tavily General search failure."
            )

        if not query or not query.strip():
            return []

        tokens = self._tokenize(query)

        matches = []

        for item in self._general_catalog:

            item_tokens = self._tokenize(
                f"{item['title']} {item.get('content', '')}"
            )

            if tokens.intersection(item_tokens):
                matches.append(item)

        return matches[:max_results]

    @staticmethod
    def _tokenize(text: str) -> Set[str]:

        words = re.findall(
            r"\b[a-zA-Z0-9_\-\.\#\+]{2,}\b",
            text.lower(),
        )

        stopwords = {
            "and",
            "the",
            "for",
            "with",
            "in",
            "to",
            "of",
            "a",
            "an",
            "on",
            "by",
            "is",
            "or",
            "tutorial",
        }

        return {
            word
            for word in words
            if word not in stopwords
        }

    def _build_youtube_catalog(self) -> List[Dict[str, Any]]:

        return [
            {
                "title": "Scala 3 Crash Course for Beginners | Rock the JVM",
                "url": "https://www.youtube.com/watch?v=scala3crash101",
                "content": (
                    "Learn Scala 3 fundamentals, syntax, immutability, "
                    "pattern matching, and functional constructs."
                ),
                "score": 0.95,
            },
            {
                "title": "Akka & Pekko Typed Actors Masterclass in 30 Minutes",
                "url": "https://www.youtube.com/watch?v=pekkoactors202",
                "content": (
                    "Hands-on guide to typed actor systems, message routing, "
                    "supervision, and asynchronous concurrency."
                ),
                "score": 0.92,
            },
            {
                "title": "Event Sourcing and CQRS with Apache Kafka Explained",
                "url": "https://www.youtube.com/watch?v=eventsourcingkafka303",
                "content": (
                    "Deep dive into distributed event logs, CQRS read models, "
                    "event projection, and stream processing."
                ),
                "score": 0.91,
            },
            {
                "title": "FastAPI REST API Authentication & JWT Step-by-Step",
                "url": "https://www.youtube.com/watch?v=fastapiauth404",
                "content": (
                    "Complete walkthrough building secure OAuth2 and JWT "
                    "authentication in FastAPI with Python."
                ),
                "score": 0.94,
            },
            {
                "title": "Git Branching and Pull Request Workflow Tutorial",
                "url": "https://www.youtube.com/watch?v=gitbranching505",
                "content": (
                    "Master git rebase, merge strategies, pull requests, "
                    "and collaborative version control."
                ),
                "score": 0.89,
            },
        ]

    def _build_general_catalog(self) -> List[Dict[str, Any]]:

        return [
            {
                "title": "Scala 3 Official Documentation and Language Guide",
                "url": "https://docs.scala-lang.org/scala3/guides/index.html",
                "content": (
                    "Authoritative guide covering traits, enums, givens, "
                    "pattern matching, and idiomatic FP."
                ),
                "score": 0.98,
            },
            {
                "title": "Apache Pekko Documentation: Typed Actor Reference",
                "url": "https://pekko.apache.org/docs/pekko/current/typed/index.html",
                "content": (
                    "Comprehensive architectural reference for building "
                    "resilient concurrent distributed systems."
                ),
                "score": 0.96,
            },
            {
                "title": "Designing Data-Intensive Applications — Event Streaming Patterns",
                "url": "https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/",
                "content": (
                    "Detailed analysis of consensus algorithms, replication "
                    "lag, and log-based event streams."
                ),
                "score": 0.97,
            },
            {
                "title": "FastAPI Security & Authentication Official Guide",
                "url": "https://fastapi.tiangolo.com/tutorial/security/",
                "content": (
                    "Official FastAPI documentation for password hashing, "
                    "Bearer tokens, and user authorization."
                ),
                "score": 0.95,
            },
        ]


# ---------------------------------------------------------------------------
# URL validation
# ---------------------------------------------------------------------------

def is_valid_youtube_url(url: str) -> bool:
    """Validates that a URL strictly belongs to YouTube."""

    if not url or not isinstance(url, str):
        return False

    clean_url = url.strip().lower()

    youtube_patterns = [
        r"^https?://(www\.)?youtube\.com/watch\?v=[\w\-]+",
        r"^https?://youtu\.be/[\w\-]+",
        r"^https?://(www\.)?youtube\.com/playlist\?list=[\w\-]+",
        r"^https?://(www\.)?youtube\.com/embed/[\w\-]+",
    ]

    return any(
        re.match(pattern, clean_url)
        for pattern in youtube_patterns
    )


# ---------------------------------------------------------------------------
# Ranking helpers
# ---------------------------------------------------------------------------

def _phrase_tokens(phrase: str) -> List[str]:
    """Tokenize a phrase while preserving meaningful words."""

    return [
        token
        for token in re.findall(
            r"\b[a-zA-Z0-9_\-\.\#\+]{2,}\b",
            phrase.lower(),
        )
    ]


def _phrase_match(
    phrase: str,
    title: str,
    description: str,
) -> bool:
    """Checks whether an important phrase occurs in title/content."""

    if not phrase:
        return False

    phrase_clean = " ".join(
        _phrase_tokens(phrase)
    )

    combined = f"{title} {description}".lower()

    return phrase_clean in combined


def _concept_overlap_score(
    concepts: List[str],
    title: str,
    description: str,
) -> float:
    """
    Measures how strongly the resource matches required concepts.

    Title matches receive more importance than description matches.
    """

    if not concepts:
        return 0.0

    title_tokens = _tokenize(title)
    content_tokens = _tokenize(description)

    matched = 0.0
    possible = 0.0

    for concept in concepts:

        concept_tokens = _tokenize(concept)

        if not concept_tokens:
            continue

        possible += 1.0

        title_overlap = concept_tokens.intersection(title_tokens)
        content_overlap = concept_tokens.intersection(content_tokens)

        if title_overlap:
            matched += 1.0

        elif content_overlap:
            matched += 0.5

    if possible == 0:
        return 0.0

    return min(1.0, matched / possible)


def _excluded_concept_penalty(
    concepts: List[str],
    title: str,
    description: str,
) -> float:
    """
    Calculates penalty for resources containing excluded concepts.

    A strong title-level match is penalized more heavily than a passing
    mention inside the description.
    """

    if not concepts:
        return 0.0

    title_tokens = _tokenize(title)
    content_tokens = _tokenize(description)

    penalty = 0.0

    for concept in concepts:

        concept_tokens = _tokenize(concept)

        if not concept_tokens:
            continue

        title_overlap = concept_tokens.intersection(title_tokens)
        content_overlap = concept_tokens.intersection(content_tokens)

        if title_overlap:
            penalty += 0.25

        elif content_overlap:
            penalty += 0.08

    return min(0.50, penalty)


def _educational_quality_score(
    url: str,
    title: str,
    description: str,
    is_youtube_stream: bool,
) -> float:
    """
    Estimates educational quality from deterministic signals.

    This is deliberately conservative. It does not claim that a domain
    is objectively good; it simply rewards common educational indicators.
    """

    text = f"{title} {description}".lower()
    domain = _extract_domain(url)

    score = 0.50

    # Strong educational indicators.
    positive_terms = [
        "lecture",
        "course",
        "lesson",
        "tutorial",
        "introduction",
        "explained",
        "fundamentals",
        "foundations",
        "guide",
        "university",
        "academic",
        "research",
        "textbook",
        "curriculum",
        "class",
    ]

    for term in positive_terms:
        if term in text:
            score += 0.025

    # High-quality educational domains.
    academic_domains = [
        ".edu",
        "apa.org",
        "britannica.com",
        "nature.com",
        "sciencedirect.com",
        "springer.com",
        "jstor.org",
        "nih.gov",
        "ncbi.nlm.nih.gov",
    ]

    if any(
        domain == d or domain.endswith(d)
        for d in academic_domains
    ):
        score += 0.20

    # YouTube needs a different quality signal.
    if is_youtube_stream:
        if any(
            term in text
            for term in [
                "lecture",
                "course",
                "university",
                "professor",
                "introduction",
                "explained",
                "fundamentals",
            ]
        ):
            score += 0.10

    # Penalize obvious entertainment / speech / generic material.
    negative_terms = [
        "full speech",
        "motivation",
        "motivational",
        "podcast",
        "reaction",
        "shorts",
        "short",
        "trailer",
        "news",
        "exam",
    ]

    for term in negative_terms:
        if term in text:
            score -= 0.08

    return max(0.0, min(1.0, score))


def _topic_relevance_score(
    request: TopicResourceDiscoveryRequest,
    title: str,
    description: str,
) -> float:
    """
    Calculates topic relevance.

    Exact topic phrase > title overlap > description overlap.
    """

    topic = request.topic_title.strip()

    if not topic:
        return 0.0

    title_lower = title.lower()
    description_lower = description.lower()
    topic_lower = topic.lower()

    # Strongest signal: exact topic phrase in title.
    if topic_lower in title_lower:
        return 1.0

    # Exact phrase anywhere.
    if topic_lower in description_lower:
        return 0.85

    topic_tokens = _tokenize(
        f"{request.topic_title} "
        f"{request.topic_description or ''}"
    )

    title_tokens = _tokenize(title)
    description_tokens = _tokenize(description)

    if not topic_tokens:
        return 0.5

    title_overlap = len(
        topic_tokens.intersection(title_tokens)
    ) / len(topic_tokens)

    description_overlap = len(
        topic_tokens.intersection(description_tokens)
    ) / len(topic_tokens)

    score = (
        title_overlap * 0.70
        + description_overlap * 0.30
    )

    return max(0.0, min(1.0, score))


def _learner_fit_score(
    request: TopicResourceDiscoveryRequest,
    title: str,
    description: str,
) -> float:
    """
    Measures fit with learner experience and learning preferences.
    """

    text = f"{title} {description}".lower()

    score = 0.5

    experience = (
        request.experience_level or ""
    ).lower()

    if experience == "beginner":

        if any(
            term in text
            for term in [
                "beginner",
                "introduction",
                "intro",
                "basics",
                "fundamentals",
                "foundations",
                "101",
            ]
        ):
            score += 0.30

        if any(
            term in text
            for term in [
                "advanced",
                "expert",
                "deep dive",
                "masterclass",
            ]
        ):
            score -= 0.15

    elif experience == "advanced":

        if any(
            term in text
            for term in [
                "advanced",
                "deep dive",
                "research",
                "masterclass",
                "expert",
            ]
        ):
            score += 0.25

    preferences = [
        preference.lower()
        for preference in request.learning_preferences
    ]

    if preferences:

        if any(
            "video" in preference
            or "visual" in preference
            for preference in preferences
        ):
            if "youtube.com" in text or "lecture" in text:
                score += 0.10

        if any(
            "reading" in preference
            or "read" in preference
            or "article" in preference
            for preference in preferences
        ):
            if any(
                term in text
                for term in [
                    "article",
                    "guide",
                    "documentation",
                    "research",
                ]
            ):
                score += 0.10

    return max(0.0, min(1.0, score))


# ---------------------------------------------------------------------------
# Main normalization + ranking
# ---------------------------------------------------------------------------

def normalize_and_rank_resources(
    raw_results: List[Dict[str, Any]],
    request: TopicResourceDiscoveryRequest,
    is_youtube_stream: bool = False,
    max_resources: int = 5,
    search_plan: Optional[SearchQueryPlan] = None,
) -> List[LearningResource]:
    """
    Normalizes, filters, deduplicates, and ranks resources.

    Ranking strategy:

        Topic relevance              35%
        Required concept alignment   20%
        Educational quality          15%
        Learner fit                  10%
        Provider score               10%
        Preferred domain             10%

    Excluded concepts and domains are applied as penalties.

    The active topic is intentionally weighted more heavily than the
    learner's broader career goal.
    """

    if not raw_results:
        return []

    seen_urls: Set[str] = set()
    normalized: List[LearningResource] = []

    plan = search_plan

    topic_tokens = _tokenize(
        f"{request.topic_title} "
        f"{request.topic_description or ''}"
    )

    goal_tokens = _tokenize(
        request.target_goal
    )

    skill_names = [
        s.skill_name.lower()
        for s in request.current_skills
    ]

    learner_prefs = [
        p.lower()
        for p in request.learning_preferences
    ]

    required_concepts = (
        plan.required_concepts
        if plan
        else []
    )

    excluded_concepts = (
        plan.excluded_concepts
        if plan
        else []
    )

    preferred_domains = (
        plan.preferred_domains
        if plan
        else []
    )

    excluded_domains = (
        plan.excluded_domains
        if plan
        else []
    )

    for item in raw_results:

        url = str(
            item.get("url", "")
        ).strip()

        title = str(
            item.get("title", "")
        ).strip()

        description = str(
            item.get(
                "content",
                item.get("description", ""),
            )
        ).strip()

        try:
            provider_score = float(
                item.get("score", 0.5)
            )
        except (TypeError, ValueError):
            provider_score = 0.5

        if not url or not title:
            continue

        # ---------------------------------------------------------------
        # URL validation
        # ---------------------------------------------------------------

        if (
            is_youtube_stream
            and not is_valid_youtube_url(url)
        ):
            continue

        domain = _extract_domain(url)

        # Hard reject excluded domains.
        if _domain_matches(
            domain,
            excluded_domains,
        ):
            continue

        # ---------------------------------------------------------------
        # Deduplication
        # ---------------------------------------------------------------

        clean_url_key = url.rstrip("/").lower()

        if clean_url_key in seen_urls:
            continue

        seen_urls.add(clean_url_key)

        # ---------------------------------------------------------------
        # Resource metadata
        # ---------------------------------------------------------------

        url_hash = hashlib.sha256(
            url.encode("utf-8")
        ).hexdigest()[:10]

        res_id = (
            f"res-{'yt' if is_youtube_stream else 'gen'}"
            f"-{url_hash}"
        )

        if is_youtube_stream:

            res_type: ResourceType = "video"
            source = "YouTube"

        else:

            res_type = _infer_resource_type(
                url,
                title,
                description,
            )

            source = _infer_source(url)

        # ---------------------------------------------------------------
        # Ranking signals
        # ---------------------------------------------------------------

        topic_score = _topic_relevance_score(
            request,
            title,
            description,
        )

        concept_score = _concept_overlap_score(
            required_concepts,
            title,
            description,
        )

        quality_score = _educational_quality_score(
            url,
            title,
            description,
            is_youtube_stream,
        )

        learner_fit = _learner_fit_score(
            request,
            title,
            description,
        )

        provider_score = max(
            0.0,
            min(
                1.0,
                provider_score,
            ),
        )

        preferred_domain_score = (
            1.0
            if _domain_matches(
                domain,
                preferred_domains,
            )
            else 0.5
        )

        excluded_penalty = _excluded_concept_penalty(
            excluded_concepts,
            title,
            description,
        )

        # ---------------------------------------------------------------
        # Goal overlap
        # ---------------------------------------------------------------

        content_tokens = _tokenize(
            f"{title} {description}"
        )

        goal_overlap = (
            len(
                goal_tokens.intersection(
                    content_tokens
                )
            )
            / max(
                1,
                len(goal_tokens),
            )
        )

        goal_overlap = min(
            1.0,
            goal_overlap,
        )

        # Goal is intentionally weak.
        # Topic relevance must dominate.
        goal_score = goal_overlap * 0.15

        # ---------------------------------------------------------------
        # Skill overlap
        # ---------------------------------------------------------------

        skill_overlap = 0.0

        for skill in skill_names:

            skill_tokens = _tokenize(skill)

            if skill_tokens.intersection(
                content_tokens
            ):
                skill_overlap = 1.0
                break

        # ---------------------------------------------------------------
        # Final weighted relevance
        # ---------------------------------------------------------------

        relevance = (
            topic_score * 0.35
            + concept_score * 0.20
            + quality_score * 0.15
            + learner_fit * 0.10
            + provider_score * 0.10
            + preferred_domain_score * 0.10
            + goal_score * 0.05
            + skill_overlap * 0.05
            - excluded_penalty
        )

        clamped_score = round(
            max(
                0.0,
                min(
                    1.0,
                    relevance,
                ),
            ),
            4,
        )

        # ---------------------------------------------------------------
        # Recommendation reasons
        # ---------------------------------------------------------------

        reasons: List[str] = []

        if topic_score >= 0.85:
            reasons.append(
                "Directly teaches the active roadmap topic"
            )

        elif topic_score >= 0.60:
            reasons.append(
                "Strong coverage of the active roadmap topic"
            )

        if concept_score >= 0.60:
            reasons.append(
                "Matches key concepts identified for this topic"
            )

        if is_youtube_stream:
            reasons.append(
                "Educational video resource"
            )

        elif quality_score >= 0.75:
            reasons.append(
                "High-quality educational reference"
            )

        if preferred_domain_score >= 1.0:
            reasons.append(
                f"Preferred educational source: {domain}"
            )

        if learner_fit >= 0.75:
            reasons.append(
                f"Fits the learner's {request.experience_level or 'current'} level"
            )

        if not reasons:
            reasons.append(
                "Relevant supplementary learning material"
            )

        # ---------------------------------------------------------------
        # Difficulty
        # ---------------------------------------------------------------

        title_lower = title.lower()

        difficulty: ResourceDifficulty

        if any(
            term in title_lower
            for term in [
                "advanced",
                "deep dive",
                "expert",
                "masterclass",
            ]
        ):
            difficulty = "advanced"

        elif any(
            term in title_lower
            for term in [
                "beginner",
                "intro",
                "introduction",
                "basics",
                "fundamentals",
                "101",
            ]
        ):
            difficulty = "beginner"

        else:
            difficulty = "intermediate"

        normalized.append(
            LearningResource(
                resource_id=res_id,
                title=title,
                url=url,
                resource_type=res_type,
                source=source,
                description=(
                    description[:300]
                    if description
                    else None
                ),
                relevance_score=clamped_score,
                difficulty=difficulty,
                estimated_time=_estimate_duration(
                    is_youtube_stream,
                    title,
                ),
                why_recommended=reasons,
            )
        )

    # -------------------------------------------------------------------
    # Final ranking
    # -------------------------------------------------------------------

    normalized.sort(
        key=lambda resource: (
            resource.relevance_score,
            resource.title.lower(),
        ),
        reverse=True,
    )

    return normalized[:max_resources]


# ---------------------------------------------------------------------------
# Tokenization
# ---------------------------------------------------------------------------

def _tokenize(text: str) -> Set[str]:

    words = re.findall(
        r"\b[a-zA-Z0-9_\-\.\#\+]{2,}\b",
        text.lower(),
    )

    stopwords = {
        "and",
        "the",
        "for",
        "with",
        "in",
        "to",
        "of",
        "a",
        "an",
        "on",
        "by",
        "is",
        "or",
        "this",
        "that",
        "from",
        "into",
        "about",
        "how",
        "what",
        "why",
        "your",
        "their",
    }

    return {
        word
        for word in words
        if word not in stopwords
    }


# ---------------------------------------------------------------------------
# Resource classification
# ---------------------------------------------------------------------------

def _infer_resource_type(
    url: str,
    title: str,
    description: str,
) -> ResourceType:

    text = (
        f"{url} "
        f"{title} "
        f"{description}"
    ).lower()

    if (
        "docs." in url
        or "documentation" in text
        or "manual" in text
    ):
        return "documentation"

    if any(
        term in text
        for term in [
            "tutorial",
            "walkthrough",
            "how-to",
            "how to",
        ]
    ):
        return "tutorial"

    if any(
        term in text
        for term in [
            "book",
            "oreilly",
            "manning",
        ]
    ):
        return "book"

    if any(
        term in text
        for term in [
            "course",
            "class",
        ]
    ):
        return "course"

    if (
        "github.com" in url
        or "project" in text
    ):
        return "project"

    return "article"


# ---------------------------------------------------------------------------
# Source classification
# ---------------------------------------------------------------------------

def _infer_source(url: str) -> str:

    domain = _extract_domain(url)

    if "docs.scala-lang.org" in domain:
        return "Scala Documentation"

    if "pekko.apache.org" in domain:
        return "Apache Pekko Docs"

    if "fastapi.tiangolo.com" in domain:
        return "FastAPI Docs"

    if "oreilly.com" in domain:
        return "O'Reilly Media"

    if "github.com" in domain:
        return "GitHub"

    return domain or "Web"


# ---------------------------------------------------------------------------
# Duration estimation
# ---------------------------------------------------------------------------

def _estimate_duration(
    is_video: bool,
    title: str,
) -> Optional[str]:

    if is_video:

        title_lower = title.lower()

        if any(
            term in title_lower
            for term in [
                "crash course",
                "masterclass",
                "full course",
            ]
        ):
            return "30-45 mins"

        if any(
            term in title_lower
            for term in [
                "lecture",
                "full lecture",
            ]
        ):
            return "30-60 mins"

        return "15-20 mins"

    return "10-15 mins read"