ai-service {
  base-url = "http://localhost:8001"
  base-url = ${?AI_SERVICE_URL}
}

http {
  interface = "0.0.0.0"
  interface = ${?HTTP_INTERFACE}
  port = 8000
  port = ${?HTTP_PORT}
}

database {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://pg-20496487-amansivastav-p1.d.aivencloud.com:20086/defaultdb?sslmode=require"
  url = ${?DATABASE_URL}
  user = "avnadmin"
  user = ${?DATABASE_USER}
  password = "AVNS_d43E8xY0DXQokLUxHFg"
  password = ${?DATABASE_PASSWORD}
  numThreads = 10
  maxConnections = 10
}

jwt {
  secret = "hades-super-secret-jwt-signing-key-2026"
  secret = ${?JWT_SECRET}
}

oauth {
  google {
    client-id = "1053667687662-gr9tddp9th9nce87ff8o7fqrefbhnqcf.apps.googleusercontent.com"
    client-id = ${?GOOGLE_CLIENT_ID}
    client-secret = "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"
    client-secret = ${?GOOGLE_CLIENT_SECRET}
  }
}

