CREATE TABLE IF NOT EXISTS riasec_results (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    realistic DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    investigative DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    artistic DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    social DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    enterprising DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    conventional DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
